// Package plugin provides types and utilities for Neovim plugin management.
package plugin

import (
	"fmt"
	"strings"
)

// GenerateHealthCheckLua generates a Lua script that runs health checks
// for the given plugins. The script outputs JSON results to stdout
// so it can be parsed by the Go CLI.
func GenerateHealthCheckLua(plugins []*Plugin) string {
	var b strings.Builder

	b.WriteString("-- Health check script generated by nvp\n")
	b.WriteString("-- Run with: nvim --headless -l <this-file>\n\n")
	b.WriteString("local results = {}\n\n")

	for _, p := range plugins {
		if !p.Enabled {
			continue
		}
		checks := DefaultHealthChecks(p)
		if len(checks) == 0 {
			continue
		}
		writePluginChecks(&b, p.Name, checks)
	}

	// Write JSON output and exit
	b.WriteString("-- Output results as JSON\n")
	b.WriteString("local json = vim.json.encode(results)\n")
	b.WriteString("io.stdout:write(json .. \"\\n\")\n")
	b.WriteString("vim.cmd('qa!')\n")

	return b.String()
}

// writePluginChecks writes the Lua code to check a single plugin.
func writePluginChecks(b *strings.Builder, pluginName string, checks []HealthCheck) {
	b.WriteString(fmt.Sprintf("-- Health checks for %s\n", pluginName))

	for _, check := range checks {
		switch check.Type {
		case HealthCheckLuaModule:
			writeLuaModuleCheck(b, pluginName, check)
		case HealthCheckCommand:
			writeCommandCheck(b, pluginName, check)
		case HealthCheckTreesitter:
			writeTreesitterCheck(b, pluginName, check)
		case HealthCheckLSP:
			writeLSPCheck(b, pluginName, check)
		}
	}
	b.WriteString("\n")
}

// writeLuaModuleCheck writes Lua code to verify a module is loadable.
func writeLuaModuleCheck(b *strings.Builder, pluginName string, check HealthCheck) {
	b.WriteString(fmt.Sprintf(`do
  local ok, _ = pcall(require, %q)
  table.insert(results, {
    plugin = %q,
    check_type = "lua_module",
    check_value = %q,
    status = ok and "healthy" or "unhealthy",
    message = ok and "module loadable" or "module not found",
  })
end
`, check.Value, pluginName, check.Value))
}

// writeCommandCheck writes Lua code to verify a Neovim command exists.
func writeCommandCheck(b *strings.Builder, pluginName string, check HealthCheck) {
	b.WriteString(fmt.Sprintf(`do
  local cmds = vim.api.nvim_get_commands({})
  local exists = cmds[%q] ~= nil
  if not exists then
    -- Also check user commands
    local ok, _ = pcall(vim.cmd, "silent! command " .. %q)
    exists = ok
  end
  table.insert(results, {
    plugin = %q,
    check_type = "command",
    check_value = %q,
    status = exists and "healthy" or "unhealthy",
    message = exists and "command available" or "command not found",
  })
end
`, check.Value, check.Value, pluginName, check.Value))
}

// writeTreesitterCheck writes Lua code to verify a treesitter parser is installed.
func writeTreesitterCheck(b *strings.Builder, pluginName string, check HealthCheck) {
	b.WriteString(fmt.Sprintf(`do
  local ok, parsers = pcall(require, "nvim-treesitter.parsers")
  local installed = false
  if ok and parsers.has_parser then
    installed = parsers.has_parser(%q)
  end
  table.insert(results, {
    plugin = %q,
    check_type = "treesitter",
    check_value = %q,
    status = installed and "healthy" or "unhealthy",
    message = installed and "parser installed" or "parser not installed",
  })
end
`, check.Value, pluginName, check.Value))
}

// writeLSPCheck writes Lua code to verify an LSP server is configured.
func writeLSPCheck(b *strings.Builder, pluginName string, check HealthCheck) {
	b.WriteString(fmt.Sprintf(`do
  local ok, lspconfig = pcall(require, "lspconfig")
  local configured = false
  if ok and lspconfig[%q] then
    configured = true
  end
  table.insert(results, {
    plugin = %q,
    check_type = "lsp",
    check_value = %q,
    status = configured and "healthy" or "unhealthy",
    message = configured and "LSP server configured" or "LSP server not configured",
  })
end
`, check.Value, pluginName, check.Value))
}
